### ISSUE TITLE
参考的论文

### ISSUE THREAD

**Issue by pprp** [coldlarry/YOLOv3-complete-pruning#1]
请问这些剪枝方法哪些论文里有？能不能推荐一个列表。谢谢！

**Comment by liuzhuang13** [comment]
@pprp  你好，这个repo的pruning算法是基于这个论文的。。。
Learning Efficient Convolutional Networks through Network Slimming
https://arxiv.org/abs/1708.06519

@coldlarry 感谢实现，请问可否在readme页面acknowledge一下我的这篇论文？

**Comment by pprp** [comment]
非常感谢！
