### ISSUE TITLE
训练自己的数据集卡住。

### ISSUE THREAD

**Issue by noobliang** [coldlarry/YOLOv3-complete-pruning#10]
为什么我训练自己的数据集，一个epoch之后就不动了，有人碰到过吗。

![Screenshot from 2019-11-07 21-06-04](https://user-images.githubusercontent.com/41882150/68391823-62605980-01a3-11ea-916b-9f0e25b78d82.png)

**Comment by coldlarry** [comment]
可以先试试训练baseline，如果baseline无法训练，说明ultralytics/yolov3的实现是有问题的，可以去该仓库的issues里看下是否有人遇到。本仓库的issues好像有人也使用自己的数据集，遇到了类似的问题。

**Comment by noobliang** [comment]
> 可以先试试训练baseline，如果baseline无法训练，说明ultralytics/yolov3的实现是有问题的，可以去该仓库的issues里看下是否有人遇到。本仓库的issues好像有人也使用自己的数据集，遇到了类似的问题。

首先非常感谢 你的回复。
这个问题太奇怪了，我本来以为显存不够，batchsize改成4还是卡住，我以为数据集的问题，但是原版yolov3可以跑，，最后换了一台电脑跑又可以了。   奇怪。
![Screenshot from 2019-11-09 00-05-57](https://user-images.githubusercontent.com/41882150/68460084-e9fca580-0241-11ea-8f33-2c02dc5050d3.png)
但是 每个epoch， test的时候会卡一下，上图 71%处。
