### ISSUE TITLE
请问有在voc2007上测试过么？我现在用ultralytics/yolov3只能达到0.7的mAP

### ISSUE THREAD

**Issue by clw5180** [coldlarry/YOLOv3-complete-pruning#11]
腾讯优图的yolov3可以达到0.79，这个我自己跑过，不知道为什么ultralytics这个版本会差好多....大佬有跑过VOC2007么？

**Comment by Angel0003** [comment]
> 腾讯优图的yolov3可以达到0.79，这个我自己跑过，不知道为什么ultralytics这个版本会差好多....大佬有跑过VOC2007么？
你用他這個剪枝的yolo3跑過其他數據集嗎

**Comment by clw5180** [comment]
> > 腾讯优图的yolov3可以达到0.79，这个我自己跑过，不知道为什么ultralytics这个版本会差好多....大佬有跑过VOC2007么？
> > 你用他這個剪枝的yolo3跑過其他數據集嗎

没
