### ISSUE TITLE
训练自己数据集到50epoch，mAP突然变为0,

### ISSUE THREAD

**Issue by noobliang** [coldlarry/YOLOv3-complete-pruning#14]
我的数据集有2千多张，分为两类，训练到50多epoch，mAP等等一直是0，后面精度也上不去。在原版yolov3跑没问题的。
![Screenshot from 2019-11-11 18-07-00](https://user-images.githubusercontent.com/41882150/68556146-fcf2be00-046b-11ea-9481-2440be11df3e.png)

**Comment by Gaondong** [comment]
@noobliang 你好 shortcut剪枝稀疏化的时候  我也遇到了同样的问题  请问你有没有解决？

**Comment by noobliang** [comment]
> @noobliang 你好 shortcut剪枝稀疏化的时候 我也遇到了同样的问题 请问你有没有解决？

你好 ,这个代码 我也没解决, 就没跑了   .但是我现在跑的是这个https://github.com/tanluren/yolov3-channel-and-layer-pruning  亲测可行, 我跑的是一个类别的.

**Comment by Gaondong** [comment]
> > @noobliang 你好 shortcut剪枝稀疏化的时候 我也遇到了同样的问题 请问你有没有解决？
> 
> 你好 ,这个代码 我也没解决, 就没跑了 .但是我现在跑的是这个https://github.com/tanluren/yolov3-channel-and-layer-pruning 亲测可行, 我跑的是一个类别的.

@noobliang  感谢回复，我尝试下，我的数据集是两个类别，没做剪枝之前，在ultralytics/yolov3上训练训练的不是很好，自己调的超参太多了
