### ISSUE TITLE
我使用和您相同的数据集以及参数训练，channel prun结果相仿，layer prun后的map微调前只有20，可能是什么问题呢？？

### ISSUE THREAD

**Issue by px2017** [coldlarry/YOLOv3-complete-pruning#35]

**Comment by coldlarry** [comment]
您好 如果是和我相同的数据集，可能是稀疏化的问题，还有可能是您代码clone的比较早？后面我对代码进行了简单修改，不知道您更新了没有。

**Comment by px2017** [comment]
谢谢您的回复！
代码是我这周二12月3号clone下来的，之后您应该没有修改代码。所以应该不是代码版本的问题。
这是稀疏化的训练结果，第一张图像是map，第二张是gamma值，看起来稀疏化训练没有什么问题，第三张是剪枝结果。
参数和您的设置都一样，唯一不同的是我没有用spp，就用的普通的yolov3，是这个导致layer prun效果差吗？



python layer_channel_prune.py --data data/oxfordhand.data --cfg cfg/yolov3-hand.cfg --weights weights/last.pt --global_percent 0.8 --layer_keep 0.01 --shortcuts 16



python layer_channel_prune.py --cfg cfg/yolov3-spp-hand.cfg --data data/oxfordhand.data --weights weights/last.pt --global_percent 0.93 --layer_keep 0.01 --shortcuts 16





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"coldlarry"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月6日(星期五) 中午12:39
收件人:&nbsp;"coldlarry/YOLOv3-complete-pruning"<YOLOv3-complete-pruning@noreply.github.com&gt;;
抄送:&nbsp;"彭响"<253358407@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [coldlarry/YOLOv3-complete-pruning] 我使用和您相同的数据集以及参数训练，channel prun结果相仿，layer prun后的map微调前只有20，可能是什么问题呢？？ (#35)




您好 如果是和我相同的数据集，可能是稀疏化的问题，还有可能是您代码clone的比较早？后面我对代码进行了简单修改，不知道您更新了没有。
