### ISSUE TITLE
保存weights在detect.py中有结果，但是用原版的darknet中没有结果

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [coldlarry/YOLOv3-complete-pruning#42]
请问作者，是保存的weights不能用在原版的darknet上，还是说我的操作有问题。
谢谢

**Comment by lxtong01** [comment]
您好，请问您这个问题解决了吗

**Comment by ZHEQIUSHUI** [comment]
没有研究啊 不过盲猜训练后的weights应该是少了点东西，up还没给方法啊

**Comment by ZHEQIUSHUI** [comment]
找到办法了，可以得到结果，但是thresh需要设置得很低。
```
VideoCapture cap(0);
Mat src;
Detector detector("YOLOv3-complete-pruning/cfg/prune_0.5_prune_0.5_yolov3-hand.cfg"
                      ,"YOLOv3-complete-pruning/weights/hand_best.weights");
while (1) {
    if(!cap.read(src))
        break;
    auto result = detector.detect(src,0.001);
    for (auto&obj:result) {
        rectangle(src,Rect(obj.x,obj.y,obj.w,obj.h),Scalar(0,0,255),2);
    }
    imshow("",src);
    if(waitKey(1)==27)
        break;
}
```

**Comment by szuRyan** [comment]
@ZHEQIUSHUI 你好，想问一下你剪裁之后生成的cfg文件是正常的嘛，能否截图看一下。我剪裁之后感觉生成的cfg文件有问题。谢谢

**Comment by git-manager** [comment]
> 找到办法了，可以得到结果，但是thresh需要设置得很低。
> 
> ```
> VideoCapture cap(0);
> Mat src;
> Detector detector("YOLOv3-complete-pruning/cfg/prune_0.5_prune_0.5_yolov3-hand.cfg"
>                       ,"YOLOv3-complete-pruning/weights/hand_best.weights");
> while (1) {
>     if(!cap.read(src))
>         break;
>     auto result = detector.detect(src,0.001);
>     for (auto&obj:result) {
>         rectangle(src,Rect(obj.x,obj.y,obj.w,obj.h),Scalar(0,0,255),2);
>     }
>     imshow("",src);
>     if(waitKey(1)==27)
>         break;
> }
> ```

您好,我也是同样的问题,设置thresh为0.00001都没用
