### ISSUE TITLE
稀疏化训练报错

### ISSUE THREAD

**Issue by a793719595** [coldlarry/YOLOv3-complete-pruning#6]
如果用第一步训练的生成的.pt文件进行稀疏化训练会报错 在把train.py第120行开始的加载chkpt['optimizer']注释掉之后就没有问题了 ，请问在稀疏化训练的时候还需要加载之前的optimizer吗，还是直接初始化一个optimizer就可以了

**Comment by liuxin0823** [comment]
作者这里说的稀疏化训练，不是对训练好的baseline进行稀疏化，是直接载入yolov3.weights然后稀疏化，详情可以看稀疏化训练用的指令（载入的是yolov3.weights）
