### ISSUE TITLE
模型剪枝后，weight转成keras的h5问题

### ISSUE THREAD

**Issue by daizhiyi** [coldlarry/YOLOv3-complete-pruning#72]
楼主您好，我能够成功实现您公布的剪枝效果非常感谢！
问题：以前我模型部署是在keras的h5基础上推进的，然后我就用tiny_yolo剪枝后的weight模型往h5转，总是报下面的错:
  File "convert.py", line 143, in _main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array
希望您帮忙解惑一下。

**Comment by ggzzzzz628** [comment]
这个问题你解决了吗？

**Comment by junze6** [comment]
将cfg文件里每个yolo层上一层的batch_normalize=0删掉
